<!DOCTYPE html>
<html lang='en'>
<head>
<title>rockbox.git - The Rockbox source code.
</title>
<meta name='generator' content='cgit '/>
<meta name='robots' content='index, nofollow'/>
<link rel='stylesheet' type='text/css' href='/cgit-data/cgit.css'/>
<link rel='shortcut icon' href='/favicon.ico'/>
<link rel='alternate' title='Atom feed' href='http://127.0.0.1:2233/cgit/rockbox.git/atom/?h=master' type='application/atom+xml'/>
<link rel='vcs-git' href='git://git.rockbox.org/rockbox.git' title='rockbox.git Git repository'/>
<link rel='vcs-git' href='http://git.rockbox.org/cgit/rockbox.git' title='rockbox.git Git repository'/>
<link rel='vcs-git' href='ssh://yourusername@gerrit.rockbox.org:29418/rockbox.git' title='rockbox.git Git repository'/>
</head>
<body>
<div id='cgit'><table id='header'>
<tr>
<td class='logo' rowspan='2'><a href='/cgit/'><img src='/cgit-data/cgit.png' alt='cgit logo'/></a></td>
<td class='main'><a href='/cgit/'>index</a> : <a title='rockbox.git' href='/cgit/rockbox.git/'>rockbox.git</a></td><td class='form'><form method='get'>
<select name='h' onchange='this.form.submit();'>
<option value='master' selected='selected'>master</option>
<option value='v3.0'>v3.0</option>
<option value='v3.1'>v3.1</option>
<option value='v3.10'>v3.10</option>
<option value='v3.11'>v3.11</option>
<option value='v3.12'>v3.12</option>
<option value='v3.13'>v3.13</option>
<option value='v3.14'>v3.14</option>
<option value='v3.15'>v3.15</option>
<option value='v3.2'>v3.2</option>
<option value='v3.3'>v3.3</option>
<option value='v3.4'>v3.4</option>
<option value='v3.5'>v3.5</option>
<option value='v3.6'>v3.6</option>
<option value='v3.7'>v3.7</option>
<option value='v3.8'>v3.8</option>
<option value='v3.9'>v3.9</option>
</select> <input type='submit' value='switch'/></form></td></tr>
<tr><td class='sub'>The Rockbox source code.
</td><td class='sub right'>Rockbox Meta-User</td></tr></table>
<table class='tabs'><tr><td>
<a href='/cgit/rockbox.git/'>summary</a><a href='/cgit/rockbox.git/refs/'>refs</a><a href='/cgit/rockbox.git/log/'>log</a><a href='/cgit/rockbox.git/tree/'>tree</a><a href='/cgit/rockbox.git/commit/'>commit</a><a href='/cgit/rockbox.git/diff/'>diff</a><a href='/cgit/rockbox.git/stats/'>stats</a></td><td class='form'><form class='right' method='get' action='/cgit/rockbox.git/log/'>
<select name='qt'>
<option value='grep'>log msg</option>
<option value='author'>author</option>
<option value='committer'>committer</option>
<option value='range'>range</option>
</select>
<input class='txt' type='search' size='10' name='q' value=''/>
<input type='submit' value='search'/>
</form>
</td></tr></table>
<div class='content'><div class='error'>Not found</div>
</div> <!-- class=content -->
<div class='footer'>generated by <a href='https://git.zx2c4.com/cgit/about/'>cgit </a> (<a href='https://git-scm.com/'>git 2.34.1</a>) at 2026-06-15 18:02:30 +0000</div>
</div> <!-- id=cgit -->
</body>
</html>
